name: daylight
main: com.frogman786.daylight
version: 0.1

commands:
  dawn:
    description: makes dawn
  day:
    description: makes day
  noon:
    description: makes noon
  dusk:
    description: makes dusk
  night:
    description: makes night