name: daylight
main: com.frogman786.daylight
version: 0.2

commands:
  dawn:
    description: makes dawn
  day:
    description: makes day
  noon:
    description: makes noon
  dusk:
    description: makes dusk
  night:
    description: makes night
  who:
    description: who is online
permissions:
    frog.*:
        description: Gives access to all frog commands
        children:
            frog.time.*: true
            frog.who.who: true
    frog.time.*:
        children:
            frog.time.dawn: true
            frog.time.day: true
            frog.time.noon: true
            frog.time.dusk: true
            frog.time.night: true
        description: all time commands
        default: op
    frog.time.dawn:
        description: dawn command
        default: false
    frog.time.day:
        description: day command
        default: false
    frog.time.noon:
        description: noon command
        default: false
    frog.time.dusk:
        description: dusk command
        default: false
    frog.time.night:
        description: night command
        default: false
    frog.who.who:
        description: who command
        default: true